### ISSUE TITLE
Time location values

### ISSUE THREAD

**Issue by adithyaknarayan** [pavan-kalyan/heartbeat-audio-CNN#1]
Does anyone have any idea how to interpret the time location data given in 'set_a_timings.csv' ?

**Comment by pavan-kalyan** [comment]
I'm guessing the time location refers to the time(in audio sample) where the S1(lub) or S2(dub) occurs.
As of now I'm not quite sure why we need this,
for now proceed without this file.
lets leave this issue open until we figure it out properly.
