### ISSUE TITLE
wave_process.m won't execute on other systems directly

### ISSUE THREAD

**Issue by pavan-kalyan** [pavan-kalyan/heartbeat-audio-CNN#3]
the wave_process.m wont run because the code contains file structure specific to one system.

Example: "t2/" folder is not present on my system.
also images folder and its subfolders need to be created in same directory if not available.

**Comment by adithyaknarayan** [comment]
Image subfolder issue taken care of and has been automated.

**Comment by pavan-kalyan** [comment]
fixed by @Alphaepsiolon as of  #4
